** Lições Aprendidas
  Utilizando os diferentes padrões de projeto e princípios SOLID, concluímos que a implementação desses algoritmos foi essencial para deixar o código do jogo mais simples, mais desacoplado e de mais fácil compreensão, permitindo a adição de possíveis novas funcionalidades sem grandes dificuldades. Ao compreender o propósito do projeto, seu funcionamento e quais tecnologias ele utilizará, a adição dos padrões de projeto pode se tornar uma arma poderosa durante o desenvolvimento e, principalmente após a conclusão das etapas iniciais, garantir um controle e manutenção do código muito mais simplificado e passível a possíveis modificações e adições futuras.

** Desafios
Ao longo do projeto foi se tornando mais claro a infinidade de maneiras diferentes de se chegar em um mesmo objetivo, e isso pode ser tanto uma vantagem como também um problema. Justamente por essa variedade de soluções, é muito fácil se perder ao longo do desenvolvimento, improvisando métodos, variáveis, classes, conceitos e muito mais. Estipular bem quais são seus objetivos e conhecer bons métodos de organização de código facilita a criação de classes e uso de conceitos de forma coerente, sem exageros e complexidade excessiva, o que ajuda a traçar um caminho mais claro para alcançar o objetivo final do projeto.